namespace Equinor.ProCoSys.PcsServiceBus;

public enum PcsTopic
{
    Action,
    CommPkgTask,
    Task,
    CommPkg,
    Ipo,
    McPkg,
    Project,
    Responsible,
    Tag,
    TagFunction,
    PunchListItem,
    Library,
    WorkOrder,
    Checklist,
    Milestone,
    WorkOrderCutoff,
    Certificate,
    WoChecklist,
    SWCR,
    SWCRSignature,
    PipingRevision,
    WoMaterial,
    WoMilestone,
    Stock,
    Document,
    CommPkgOperation,
    PipingSpool,
    LoopContent,
    Query,
    QuerySignature,
    CallOff,
    CommPkgQuery,
    HeatTrace
}
