namespace Equinor.ProCoSys.PcsServiceBus;

public static class PcsTopicConstants
{
    public const string Action = "Action";
    public const string CommPkgTask = "CommPkgTask";
    public const string Task = "Task";
    public const string CommPkg = "CommPkg";
    public const string Ipo = "Ipo";
    public const string McPkg = "McPkg";
    public const string Project = "Project";
    public const string Responsible = "Responsible";
    public const string Tag = "Tag";
    public const string TagFunction = "TagFunction";
    public const string PunchListItem = "PunchListItem";
    public const string Library = "Library";
    public const string WorkOrder = "WorkOrder";
    public const string Checklist = "Checklist";
    public const string McPkgMilestone = "McPkgMilestone";
    public const string WorkOrderCutoff = "WorkOrderCutoff";
    public const string Certificate = "Certificate";
    public const string WoChecklist = "WoChecklist";
    public const string SWCR = "Swcr";
    public const string SWCRSignature = "SwcrSignature";
    public const string PipingRevision = "PipingRevision";
    public const string WoMaterial = "WoMaterial";
    public const string WoMilestone = "WoMilestone";
    public const string Stock = "Stock";
    public const string Document = "Document";
    public const string CommPkgOperation = "CommPkgOperation";
    public const string PipingSpool = "PipingSpool";
    public const string LoopContent = "LoopContent";
    public const string Query = "Query";
    public const string QuerySignature = "QuerySignature";
    public const string CallOff = "CallOff";
    public const string CommPkgQuery = "CommPkgQuery";
    public const string HeatTrace = "HeatTrace";
    public const string HeatTracePipeTest = "HeatTracePipeTest";
    public const string CommPkgMilestone = "CommPkgMilestone";
    public const string TagEquipment = "TagEquipment";
    public const string SwcrType = "SwcrType";
    public const string SwcrOtherReference = "SwcrOtherReference";
    public const string SwcrAttachment = "SwcrAttachment";
    public const string LibraryField = "LibraryField";
    public const string Milestone = "Milestone";
    public const string Person = "Person";
    public const string IpoInvitation = "IpoInvitation";
    public const string IpoInvitationComment = "IpoInvitationComment";
    public const string IpoInvitationParticipant = "IpoInvitationParticipant";
    public const string IpoInvitationMcPkg = "IpoInvitationMcPkg";
    public const string IpoInvitationCommPkg = "IpoInvitationCommPkg";
}
