version: '3.4'

services:
  equinor.procosys.bussender.worker:
    image: ${DOCKER_REGISTRY-}equinorprocosysbussenderworker
    build:
      context: .
      dockerfile: src/Equinor.ProCoSys.BusSender.Worker/Dockerfile     
    environment:
      - Local=True
      - AZURE_LOG_LEVEL=verbose
      - DOTNET_ENVIRONMENT=Development
      - AZURE_CLIENT_SECRET=${someArg}
      - AZURE_CLIENT_ID=21f9fa4f-d419-45aa-9070-ddfb6fb86b45
      - AZURE_TENANT_ID=3aa4a235-b6e2-48d5-9195-7fcf05b459b0
    volumes:
      - $APPDATA\Microsoft\UserSecrets:/root/.microsoft/usersecrets/
      - ~/.azure:/root/.azure 